; put ALL THE CONSTANTS HERE 

[DEFAULT]

PAGE_TITLE = Langgraph: Build Stateful Agentic AI graph
LLM_OPTIONS = Groq
USECASE_OPTIONS = Basic ChatBot, ChatBot with Tools, Ai News, Blog Generator
GROQ_MODEL_OPTIONS = llama-3.1-8b-instant, llama-3.3-70b-versatile, groq/compound, groq/compound-mini

